theme = "dracula"

[editor]
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding", "file-line-ending"]

[editor.cursor-shape]
select = "underline"

[editor.file-picker]
git-ignore = false
